name: "Angular frontend application"
on:
  push:
    branches: [ 'main' ]
    paths: 
      - './frontend/**'
      - '.github/workflows/frontend.yml'
  pull_request:
    branches: [ 'main' ]
    paths: 
      - './frontend/**'
      - '.github/workflows/frontend.yml'
  
jobs:
  build-angular:
    defaults:
      run:
        working-directory: ./frontend
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os:
          - 'ubuntu-latest'
        node-version: 
          - '18.3.x'
    steps:
      - uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('frontend/**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm install and build
        run: |
          npm install
          npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          aws-secret-access-key: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          aws-region: eu-central-1

      # - id: install-aws-cli
      #   uses: unfor19/install-aws-cli-action@v1.0.3
      #   with:
      #     version: 2     # default
      #     verbose: false # default
      #     arch: amd64    # allowed values: amd64, arm64
      #     rootdir: ""    # defaults to "PWD"
      #     workdir: ""    # defaults to "PWD/unfor19-awscli"

      - name: deploy to S3
        run: aws s3 sync ./dist/* s3://${{ secrets.FRONTEND_S3_BUCKET }} --delete

      # - name: Deploy
      #   if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      #   uses: reggionick/s3-deploy@v3
      #   with:
      #     folder: ./dist
      #     bucket: ${{ secrets.FRONTEND_S3_BUCKET }}
      #     bucket-region: ${{ secrets.FRONTEND_S3_BUCKET_REGION }}
      #     dist-id: ${{ secrets.FRONTEND_CLOUDFRONT_DISTRIBUTION_ID }}
      #     invalidation: /
      #     delete-removed: true
      #     no-cache: true
      #     private: true